### ISSUE TITLE
CUDA out of memory ( with solution )

### ISSUE THREAD

**Issue by matpalm** [hardmaru/image-notebook#1]
FYI for anyone experiencing OOM on the upsampling you can run this using `xformers`

ref: https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler/discussions/2

which boils down to ...

```
pip3 install xformers triton
```

then including `set_use_memory_efficient_attention_xformers`

```
uppipe = StableDiffusionUpscalePipeline.from_pretrained(upscaler_repo_id, torch_dtype=torch.float16)
uppipe.set_use_memory_efficient_attention_xformers(True)
uppipe = uppipe.to("cuda")
```

**Comment by hardmaru** [comment]
Thanks, have incorporated this in the notebook.

Also tried to go from 512 -> 2048 (before downsampling back to 1024 / pasting orig), which takes longer, but is higher quality than going from 512 -> 256 -> 1024 (and then pasting orig)
